os:
    - linux

language: c

compiler:
    - gcc
    - clang

matrix:
    include:
    - env: CXX=g++ CC=gcc
    - env: CXX=clang++ CC=clang

install:
    - sudo apt-get install -qq cmake

before_script:
    - mkdir -p build
    - cd build
    - cmake ../CMakeLists.txt

script:
    - make all

notifications:
    email:
        on_success: never
        on_failure: always
