os:
    - linux
    - osx

language: c

compiler:
    - gcc
    - clang

env: 
    - CXX=g++ CC=gcc
    - CXX=clang++ CC=clang

install:
    - sudo apt-get install -qq cmake

script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make all

notifications:
    email:
        on_success: never
        on_failure: always
