checkdef (){
	if [ "${!1}" = "y" ];
	then
		echo "#define $1 1" >> $2
	else
		echo "// $1 is not defined" >> $2
	fi
	echo >> $2
}

usage(){
	echo Usage : loadconfig.sh input_config_filename output_header_filename
	echo Example : loadconfig.sh defconfig config.h
}

CONFIG=configs/$1

if [ -z "$CONFIG" ];
then
	echo Please specify a config file to continue!
	usage
elif [ ! -e "$CONFIG" ];
then
	echo File $1 does not exist!
	usage
elif [ -z "$2" ];
then
	echo Please specify an output file to continue!
	usage
else
	HEADER=include/$2
	if [ -e $HEADER ];
	then
		echo A header file with the same name exists already!
		echo Backing up previous $2..
		mv $HEADER $HEADER.bak
	fi
	
	echo Loading configuration file..

	. $CONFIG

	echo Defining header name..

	NAME=""

	EXT=""

	IFS='.' read -ra EXT <<< "$2"

	for i in "${EXT[@]}"; do
		NAME=$NAME"_"${i^^}
	done

	echo //Automatically generated by loadconfig >> $HEADER
	echo "#ifndef $NAME" >> $HEADER
	echo "#define $NAME" >> $HEADER
	echo >> $HEADER

	echo Checking configuration options..

	for i in CONFIG_LINEAR_QUEUE CONFIG_DEQUE CONFIG_PRIORITY_QUEUE
	do
		checkdef $i $HEADER
	done

	echo "#endif" >> $HEADER

	echo $2 created successfully..
fi
