#!/bin/bash
nocol='\033[0m'
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'

printincol(){
	echo -e "$2 $1 $nocol"
}

printerror(){
	printincol $1 $red
}

printinfo(){
	printincol $1 $blue
}

printwarning(){
	 printincol $1 $yellow
}

usage(){
	echo -e "$red Usage : bash createconfig.sh input_desc_file output_config_file $nocol"
}

if [ "$1" = "" ];
then
	echo -e "$red Please specify a desc file $nocol"
	usage
elif [ ! -e "$1" ];
then
	echo -e "$red Input file does not exist! $nocol"
	usage
elif [ "$2" = "" ];
then
	echo -e "$red Please specify an output file $nocol"
	usage
else
	echo "# Automatically generated by createconfig" > $2
	while IFS='' read -r line || [[ -n $line ]];
        	do
			if [[ ! $line = "#"* ]];
			then
        	        	# Split each line in "="
                		IFS='=' read -ra PART <<< $line
        	        	# Check if size of array is 2
	    			if [ "${#PART[@]}" = "2" ];
       	       		 	then
                	        	# Store the config name
					ITEMS=${PART[0]}
					# Check the value
                        		VAL=${PART[1]}
					echo -e "$blue $VAL $nocol\n (y/n) > "
					read ANS < /dev/tty
					
					IFS=',' read -ra ITEM <<< $ITEMS
					for j in "${ITEM[@]}"
					do
                        			case $ANS in
                        			[Yy]* )
							echo "$j=y" >> $2;;
                        			* )
                                			echo "$j=n" >> $2;;
                        			esac
					done
					fi
                	fi
        done < $1
	echo -e "$blue Config file $2 generated.. $nocol"
fi
