#!/bin/bash

usage(){
	echo "bash createconfig.sh input_desc_file output_config_file"
}

if [ "$1" = "" ];
then
	echo "Please specify a desc file"
	usage
elif [ ! -e "$1" ];
then
	echo "Input file does not exist!"
	usage
elif [ "$2" = "" ];
then
	echo "Please specify an output file"
	usage
else
	echo "# Automatically generated by createconfig" > $2
	while IFS='' read -r line || [[ -n $line ]];
        	do
			if [[ ! $line = "#"* ]];
			then
        	        	# Split each line in "="
                		IFS='=' read -ra PART <<< $line
        	        	# Check if size of array is 2
	    			if [ "${#PART[@]}" = "2" ];
       	       		 	then
                	        	# Store the config name
					ITEM=${PART[0]}
					# Check the value
                        		VAL=${PART[1]}
					printf "$VAL\n(y/n) > "
					read  ANS < /dev/tty
                        		case $ANS in
                        		[Yy]* )
                                		echo "$ITEM=y" >> $2;;
                        		* )
                                		echo "$ITEM=n" >> $2;;
                        		esac
					fi
                	fi
        done < $1
	echo "Config file $2 generated.."
fi
