//Automatically generated by loadconfig
#ifndef _QUEUE_CONFIG_H
#define _QUEUE_CONFIG_H

// CONFIG_LINEAR_QUEUE is not defined

// CONFIG_DEQUE is not defined

#define CONFIG_PRIORITY_QUEUE

#define CONFIG_NODE_INTEGER

#define CONFIG_NODE_REAL

// CONFIG_NODE_CHARACTER is not defined

#define MULVALUE

#define DEF_QUEUE_TYPE PRIORITY

#endif
