//Automatically generated by loadconfig
#ifndef _QUEUE_TESTCONFIG_H
#define _QUEUE_TESTCONFIG_H

#define CONFIG_LINEAR_QUEUE

// CONFIG_DEQUE is not defined

// CONFIG_PRIORITY_QUEUE is not defined

#define CONFIG_NODE_REAL

// CONFIG_NODE_CHAR is not defined

#endif
