//Automatically generated by loadconfig
#ifndef _QUEUE_CONFIG_H
#define _QUEUE_CONFIG_H

#define CONFIG_LINEAR_QUEUE

#define CONFIG_DEQUE

#define CONFIG_PRIORITY_QUEUE

#define CONFIG_NODE_INTEGER

#define CONFIG_NODE_REAL

#define CONFIG_NODE_CHARACTER

#define MULVALUE

#define MULQUEUE

#endif
