//Automatically generated by loadconfig
#ifndef _TESTCONFIG_H
#define _TESTCONFIG_H

#define CONFIG_LINEAR_QUEUE

#define CONFIG_DEQUE

// CONFIG_PRIORITY_QUEUE is not defined

#define CONFIG_NODE_INTEGER

#define CONFIG_NODE_REAL

// CONFIG_NODE_CHARACTER is not defined

#define MULVALUE

#define MULQUEUE

#endif
